# Generated by Django 5.0.4 on 2024-06-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_savedinfo_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedinfo',
            name='month',
            field=models.CharField(default='January', max_length=50),
        ),
    ]
