# Generated by Django 5.0.4 on 2024-06-13 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_savedinfo_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedinfo',
            name='country',
        ),
    ]
