# Generated by Django 5.0.4 on 2024-06-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_savedinfo_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedinfo',
            name='itinName',
            field=models.CharField(default='Itinerary name', max_length=100),
        ),
    ]
